/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.81.0
  Forc version: 0.49.3
  Fuel-Core version: 0.22.1
*/

export type { NftContractAbi } from './NftContractAbi';

export { NftContractAbi__factory } from './factories/NftContractAbi__factory';
